export { default as Post } from './Post/Post'
export { default as AddPost } from './AddPost'
export { default as PostList } from './PostList'
export { default as Home } from './Home'
export { default as Button } from './Button'
export { default as Ctrl } from './Ctrl'
export { default as FormInput } from './FormInput'